spring:
  application:
    name: FitMaster

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/fitmaster_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123444}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    detect-encoding: true


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    open-in-view: false #for prodection  #هي موجودة بالنوتس ارجع راجعها
    properties:
      hibernate:




  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  app:
    jwtSecret: ${JWT_SECRET:SGVsbG9Xb3JsZFRoaXNJc0FTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25XaXRoU3ByaW5nQm9vdA==}
    jwtExpirationMs: 86400000
    jwtCookieName: springBootEcom

exercises:
  images:
    path: ${EXERCISES_PATH:D:/Graduation/GP2/FitMaster/exercises/}

gemini:
  api:
    key: ${GEMINI_API_KEY:AIzaSyAQ17xrozZ7uj_gZQ8Wb-e-2nnts2iu8ow}
    url:  ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dakuwdt6l}
  api-key: ${CLOUDINARY_API_KEY:176965344899189}
  api-secret: ${CLOUDINARY_API_SECRET:sNI8zrxgU5YDYQ0_EO8kaJ18ias}