spring:
  application:
    name: FitMaster

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    detect-encoding: true


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    open-in-view: false #for prodection  #هي موجودة بالنوتس ارجع راجعها
    properties:
      hibernate:




  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000
    jwtCookieName: springBootEcom

exercises:
  images:
    path: ${EXERCISES_PATH:D:/Graduation/GP2/FitMaster/exercises/}



cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

groq:
  api:
    key: ${GROQ_API_KEY}
    url: https://api.groq.com/openai/v1/chat/completions